# This is a basic workflow to help you get started with Actions

name: Firebase function deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ feat/ci_test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # And of course we need to goto our functions folder to deploy
    - name: Install npm packages
      run: |
        yarn

    ## Save Service Account Key
    - name: write Firebase service account key (from secrets to json)
      id: create-json
      uses: jsdaniell/create-json@v1.2.1
      with:
          name: "serviceAccountKey.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          dir: "./packages/backend/"
    
    # Deploying the functions to firebase
    - name:  Deploy to Firebase
      run: npx firebase deploy --only functions --project prod
      working-directory: "./packages/backend/"
      env:
          GOOGLE_APPLICATION_CREDENTIALS: "./serviceAccountKey.json"